dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  secure: QFnUQkoQBFsmNrYzpXAWRexL0dP2clngVzfW3DtIRPEESwb+vfxNZ1WizRa60LT01nynR6ZhpwvnLEm0FiBC3w7/snmsPMlrQCeMsEIviwrSgRq0D6gjUbogXp20aR3XN/fDjyx/TAHxOoqXhyl3M+F8T6nz+vjn5aRnex1Qke3yrQ4xdjz2mhcNNnpgRH9DTiNNmeEy3DDmHIVow/9+2DonfoApyYrH9uAWUc61eiRNE8pkfrKP4QuJw2zL3PVWXEftfmnwJYNl871ptbPGk6okvJqR64Y1ylfk18uW2yLwgth2/7uTm1K7DcHIUpNqGKTpvpEzX8A05sL/OoLt7q+dSGCyJmjI/6HoEIUJIgnAN8FOYHZzZSAxuXs6l2S7H77SODPG95+71dYHLxaqcR0umYmiMJspbuHu6vJoZHMXHG4h93E8YY1gGARsajp7tPbjZyrsNw6Xux9exd8krRZ/LGXOeVL/ArwN914ZwUXMYfpOpTif3142KLnYcNLwDFdGxPQjHDyUSM/zV+XZfjMb3aXYcOQGOXzO13NlLJP2NpZ8cdPzJPSjSqAhA2EjntX7jJz+J4/HTYpLwv1Y5DqoBMzRdu3rJlbmYyq2oTk20siNAOYuDcyl9X8+Nx6qgtBeKG4nRzDoD8iJLq/K3oE7/xRGWuqfugR1jMbyNIQ=
