---
# tasks file for app
- name: Show facts DB server
  debug:
    var: item
  with_items:
    - "{{ db_host_name }}"
    - "{{ db_host }}"

- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
    owner: appuser
    group: appuser
    force: yes
  notify: reload puma
  changed_when: true

- name: enable puma
  systemd: name=puma enabled=yes
