# puma tasks
- name: Show facts DB server
  debug:
    msg: DB host={{ item }}
  with_items:
    - "{{ db_host }}"

- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    force: yes
  notify: reload puma
  changed_when: true

- name: enable puma
  systemd: name=puma enabled=yes daemon_reload=yes
