- name: Install Install Ruby Ğ¸ Bundler packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby
