- name: Install MongoDB
  # hosts: all - для packer, т.к. при сборке образа нет групп ansible
  hosts: all
  become: true
  tasks:
    - name: Add an apt key MongoDB repo
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
    
    - name: Add MongoDB repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: mongodb-org-3.2
        update_cache: yes

    - name: Install MongoDB packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - mongodb-org

    - name: Enable service MongoDB
      systemd:
        name: mongod
        enabled: yes
